### ISSUE TITLE
GSOC Contribution

### ISSUE THREAD

**Issue by 11-aryan** [ML4SCI/ML4SCI_GSoC#5]
This is my first participation in GSOC, and I have no idea how things work.
Could someone please guide me on contributing and project timelines in GSOC

**Comment by Anky209e** [comment]
Yup,I am also interested in working on this topic and some more.
On google's site it says that students can submit their application after 4th April.
So,i guess we have to weight till then.

**Comment by pratyaksh177** [comment]
I want to contribute to this Project , but I found there is no Issue. Can anyone please guide me.

**Comment by indrasn0wal** [comment]
Hello, everyone. I want to contribute to this project but there is no issue available. Can anyone help me.

**Comment by latifbhatti** [comment]
Machine learning is my interesting field. So I want to contribute on this project . Assign me task.

**Comment by emanueleusai** [comment]
Please check the website for tests and project ideas

**Comment by latifbhatti** [comment]
I want to contribute in Social street smart large. Please guide me
more.because I want to enhance my chance to select in gsoc program
